### ISSUE TITLE
add janusweb to frontend

### ISSUE THREAD

**Issue by madjin** [jasmineroberts/metaverse-stack#3]
https://github.com/jasmineroberts/metaverse-stack#frontend

Link: https://github.com/jbaicoianu/janusweb

similar to aframe but comes with many outta the box features like networking / avatars / text + voice chat etc
reminds me of ubuntu desktop vs linux from scratch sorta

**Comment by jasmineroberts** [comment]
Thank you for your suggestion! Added it!
